import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/app/context/Cartcontext";
import { UserProvider } from "@/app/context/Usercontext";
import LayoutWrapper from "@/hooks/LayoutWrapper";
import { ReactQueryProvider } from "@/app/context/Provider";
import { FormProvider } from "@/app/context/Formcontext";
import { AuthProvider } from "@/app/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Afrochow",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>{/* Include metadata, styles, etc. */}</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <AuthProvider>
          <FormProvider>
            <CartProvider>
              <UserProvider>
                <LayoutWrapper>{children}</LayoutWrapper>
              </UserProvider>
            </CartProvider>
          </FormProvider>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
